
branches:
  only:
  - master
  - /^v.*$/
  - /^issue-\d+/


sudo: false

services:
  - docker

script:
  - |
    export VERSION=${TRAVIS_TAG:-"latest"}
    make docker VERSION=${VERSION}
    echo ${DOCKER_PASSWORD} | docker login --password-stdin -u ${DOCKER_USER}
    if [[ (! -z ${TRAVIS_TAG} || ${TRAVIS_BRANCH} == "master") && ${TRAVIS_PULL_REQUEST} == false ]]; then
      make docker-push VERSION=${VERSION}
    elif [[ ${TRAVIS_PULL_REQUEST} == "true" ]]; then
      make docker-push VERSION=${TRAVIS_PULL_REQUEST_BRANCH}
    fi